load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "mylib",
    srcs = [
        "mylib.cpp",
    ],
    hdrs = [
        "mylib.hpp",
    ],
    visibility = ["//visibility:public"],
)
